name: Deploy to Cloud Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.build_vars.outputs.SHORT_SHA }}
      image_name: ${{ steps.build_vars.outputs.IMAGE_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: "Generate Build Variables"
        id: build_vars
        run: |
          echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=europe-west1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/docker-repo/keystore-service:${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCLOUD_SA_KEY }}"

      - name: "Setup Google Cloud CLI"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 527.0.0"

      - name: "Build and Push Docker Image"
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          docker buildx create --name multiarch-builder --use
          docker buildx build --platform linux/amd64,linux/arm64 -f ci/images/Dockerfile -t ${{ steps.build_vars.outputs.IMAGE_NAME }} --push .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: [www, develop-wl, base-wl]
    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCLOUD_SA_KEY }}"

      - name: "Setup Google Cloud CLI"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 527.0.0"

      - name: "Deploy to ${{ matrix.server }} Server"
        run: |
          gcloud compute ssh root@${{ matrix.server }} \
            --project ${{ secrets.GCLOUD_PROJECT_ID }} \
            --zone europe-west1-b \
            --quiet \
            --force-key-file-overwrite \
            --command="/app/elacity/arch/bin/update.py keystore ${{ needs.build.outputs.image_name }}"
