name: Deploy to Cloud Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.build_vars.outputs.SHORT_SHA }}
      image_name: ${{ steps.build_vars.outputs.IMAGE_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: "Generate Build Variables"
        id: build_vars
        run: |
          SHORT_SHA=${GITHUB_SHA:0:7}
          IMAGE_NAME="europe-west1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/docker-repo/keystore-service:${SHORT_SHA}"
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "Generated SHORT_SHA: ${SHORT_SHA}"
          echo "Generated IMAGE_NAME: ${IMAGE_NAME}"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCLOUD_SA_KEY }}"

      - name: "Setup Google Cloud CLI"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 527.0.0"

      - name: "Build and Push Docker Image"
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          docker buildx create --name multiarch-builder --use
          docker buildx build --platform linux/amd64,linux/arm64 -f ci/images/Dockerfile -t ${{ steps.build_vars.outputs.IMAGE_NAME }} --push .
          echo "Built and pushed image: ${{ steps.build_vars.outputs.IMAGE_NAME }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - server: www
            path: /app/elacity/arch/bin/update.py
          - server: develop-wl
            path: /app/elacity/arch/bin/update.py
          - server: base-wl
            path: /app/elacity/base/bin/update.py
    steps:
      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCLOUD_SA_KEY }}"

      - name: "Setup Google Cloud CLI"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 527.0.0"
          install_components: "gcloud,gsutil"

      - name: "Verify Authentication"
        run: |
          gcloud auth list
          gcloud config list project

      - name: "Deploy to ${{ matrix.server }} Server"
        run: |
          echo "Deploying to ${{ matrix.server }} with image: ${{ needs.build.outputs.image_name }}"
          echo "Using script path: ${{ matrix.path }}"
          gcloud compute ssh root@${{ matrix.server }} \
            --project ${{ secrets.GCLOUD_PROJECT_ID }} \
            --zone europe-west1-b \
            --quiet \
            --force-key-file-overwrite \
            --command="${{ matrix.path }} keystore ${{ needs.build.outputs.image_name }}"
